// <auto-generated />
using GestionProductosClientes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionProductosClientes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002211443_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("GestionProductosClientes.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoMaterno = "Lopez",
                            ApellidoPaterno = "García",
                            Nombre = "Luis",
                            Telefono = "5512345678"
                        },
                        new
                        {
                            Id = 2,
                            ApellidoMaterno = "Sánchez",
                            ApellidoPaterno = "Pérez",
                            Nombre = "María",
                            Telefono = "5523456789"
                        },
                        new
                        {
                            Id = 3,
                            ApellidoMaterno = "Diaz",
                            ApellidoPaterno = "Ramírez",
                            Nombre = "Carlos",
                            Telefono = "5534567890"
                        },
                        new
                        {
                            Id = 4,
                            ApellidoMaterno = "Ortiz",
                            ApellidoPaterno = "Martínez",
                            Nombre = "Ana",
                            Telefono = "5545678901"
                        },
                        new
                        {
                            Id = 5,
                            ApellidoMaterno = "Ruiz",
                            ApellidoPaterno = "Hernández",
                            Nombre = "Jorge",
                            Telefono = "5556789012"
                        });
                });

            modelBuilder.Entity("GestionProductosClientes.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Sabor vainilla 1kg",
                            Existencia = 12,
                            Nombre = "Proteína Whey",
                            Precio = 899.99m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Par de mancuernas recubiertas",
                            Existencia = 8,
                            Nombre = "Mancuerna 5kg",
                            Precio = 599.50m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Set 3 niveles",
                            Existencia = 25,
                            Nombre = "Bandas Elásticas",
                            Precio = 199.00m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Antideslizante 6mm",
                            Existencia = 30,
                            Nombre = "Colchoneta Yoga",
                            Precio = 249.90m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Talla M",
                            Existencia = 20,
                            Nombre = "Guantes de gym",
                            Precio = 149.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
